development:
  adapter: mysql2
  database: ami_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: ami_test
  username: root
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: ami_production
  username: root
  password: 
  encoding: utf8
